IF (NOT _macroLogFeatureAlreadyIncluded)
    SET(_file ${CMAKE_BINARY_DIR}/MissingRequirements.txt)
    IF (EXISTS ${_file})
        FILE(REMOVE ${_file})
    ENDIF (EXISTS ${_file})

    SET(_file ${CMAKE_BINARY_DIR}/EnabledFeatures.txt)
    IF (EXISTS ${_file})
        FILE(REMOVE ${_file})
    ENDIF (EXISTS ${_file})

    SET(_file ${CMAKE_BINARY_DIR}/DisabledFeatures.txt)
    IF (EXISTS ${_file})
        FILE(REMOVE ${_file})
    ENDIF (EXISTS ${_file})

    SET(_macroLogFeatureAlreadyIncluded TRUE)
ENDIF (NOT _macroLogFeatureAlreadyIncluded)

MACRO(MACRO_LOG_FEATURE _var _package _description _url ) # _required _minvers _comments)
    SET(_required "${ARGV4}")
    SET(_minvers "${ARGV5}")
    SET(_comments "${ARGV6}")

    IF (${_var})
        SET(_LOGFILENAME ${CMAKE_BINARY_DIR}/EnabledFeatures.txt)
    ELSE (${_var})
        SET(_LOGFILENAME ${CMAKE_BINARY_DIR}/DisabledFeatures.txt)
    ENDIF (${_var})

    FILE(APPEND ${_LOGFILENAME} "${_package}\n")
    FILE(APPEND ${_LOGFILENAME} "  DESCRIPTION: ${_description}\n")
    IF (NOT "${_url}" STREQUAL "")
        FILE(APPEND ${_LOGFILENAME} "  URL: ${_url}\n")
    ENDIF (NOT "${_url}" STREQUAL "")
    IF (NOT "${_minvers}" STREQUAL "")
        FILE(APPEND ${_LOGFILENAME} "  MIN_VERSION: ${_minvers}\n")
    ENDIF (NOT "${_minvers}" STREQUAL "")
    IF (NOT "${_comments}" STREQUAL "")
        FILE(APPEND ${_LOGFILENAME} "  COMMENTS: ${_comments}\n")
    ENDIF (NOT "${_comments}" STREQUAL "")
    FILE(APPEND ${_LOGFILENAME} "\n")

    IF (NOT ${_var} AND _required)
        SET(_file ${CMAKE_BINARY_DIR}/MissingRequirements.txt)
        FILE(APPEND ${_file} "${_package}\n")
        FILE(APPEND ${_file} "  DESCRIPTION: ${_description}\n")
        IF (NOT "${_url}" STREQUAL "")
            FILE(APPEND ${_file} "  URL: ${_url}\n")
        ENDIF (NOT "${_url}" STREQUAL "")
        IF (NOT "${_minvers}" STREQUAL "")
            FILE(APPEND ${_file} "  MIN_VERSION: ${_minvers}\n")
        ENDIF (NOT "${_minvers}" STREQUAL "")
        IF (NOT "${_comments}" STREQUAL "")
            FILE(APPEND ${_file} "  COMMENTS: ${_comments}\n")
        ENDIF (NOT "${_comments}" STREQUAL "")
        FILE(APPEND ${_file} "\n")
        SET(_macroLogFeatureMissingRequired TRUE)
    ENDIF (NOT ${_var} AND _required)
ENDMACRO(MACRO_LOG_FEATURE)


MACRO(MACRO_DISPLAY_FEATURE_LOG)
    MESSAGE(STATUS "-----------------------------------------------------------------------------")
    MESSAGE(STATUS "-- The following OPTIONAL packages have been found on your system.")
    MESSAGE(STATUS "-- Consider installing them to enable more features.")
    MESSAGE(STATUS "-----------------------------------------------------------------------------")
    IF (EXISTS ${CMAKE_BINARY_DIR}/EnabledFeatures.txt)
        FILE(READ ${CMAKE_BINARY_DIR}/EnabledFeatures.txt _contents)
        MESSAGE(STATUS "${_contents}")
    ENDIF (EXISTS ${CMAKE_BINARY_DIR}/EnabledFeatures.txt)

    MESSAGE(STATUS "-----------------------------------------------------------------------------")
    MESSAGE(STATUS "-- The following OPTIONAL packages could NOT be located on your system.")
    MESSAGE(STATUS "-- Consider installing them to enable more features.")
    MESSAGE(STATUS "-----------------------------------------------------------------------------")
    IF (EXISTS ${CMAKE_BINARY_DIR}/DisabledFeatures.txt)
        FILE(READ ${CMAKE_BINARY_DIR}/DisabledFeatures.txt _contents)
        MESSAGE(STATUS "${_contents}")
    ENDIF (EXISTS ${CMAKE_BINARY_DIR}/DisabledFeatures.txt)

    IF (_macroLogFeatureMissingRequired)
        MESSAGE(FATAL_ERROR "-----------------------------------------------------------------------------\\n" "-- The following REQUIRED packages could NOT be located on your system.\n" "-- Please install them before continuing this software installation.\n" "-- If you are in Windows, try passing -DOGRE_DEPENDENCIES_DIR=<path to dependencies>\n" "-----------------------------------------------------------------------------\\n" "${_contents}")
    ENDIF (_macroLogFeatureMissingRequired)
ENDMACRO(MACRO_DISPLAY_FEATURE_LOG)
